<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <name>Trabalho de DM 110 - Rest API</name>
  <description>Rest API project of DM 110</description>
  <properties></properties>
  <parent>
    <groupId>br.inatel.dm110</groupId>
    <artifactId>trabalho-parent</artifactId>
    <version>1.0</version>
  </parent>

  <groupId>br.inatel.dm110</groupId>
  <artifactId>trabalho-api</artifactId>
  <packaging>jar</packaging>
  
  <build>
  	<plugins>
  		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
	        <artifactId>maven-resources-plugin</artifactId>
			<executions>
	          <execution>
	            <id>copy-generated-doc-to-parent</id>
	            <phase>package</phase>
	            <goals>
	              <goal>copy-resources</goal>
	            </goals>
	            <configuration>
	              <outputDirectory>../docs/uml</outputDirectory>
	              <resources>
	                <resource>
	                  <directory>${project.build.directory}/generated-docs</directory>
	                  <includes>
	                    <include>${project.artifactId}-class-diagram.puml</include>
	                  </includes>
	                </resource>
	              </resources>
	              <overwrite>true</overwrite>
	            </configuration>
            </execution>
          </executions>		
  		</plugin>
  	</plugins>
  </build>

  <dependencies>
		<dependency>
			<groupId>jakarta.platform</groupId>
			<artifactId>jakarta.jakartaee-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
  </dependencies>
</project>
