--script do banco

-- Tabela CUSTOMER
CREATE TABLE Customer (
    cpf VARCHAR(11) NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    birthdate DATE NOT NULL,
    gender CHAR(1) NOT NULL CHECK (gender IN ('M', 'F')),
    email VARCHAR(100) NOT NULL UNIQUE,
    cep VARCHAR(8) NOT NULL
);

-- Tabela AUDIT
CREATE TABLE Audit (
    identifier INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    registerCode VARCHAR(11) NOT NULL,
    operation VARCHAR(6) NOT NULL CHECK (operation IN ('create', 'update')),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
